# Generated by Django 4.1.2 on 2022-10-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name="nick_name",
        )
    ]
