# Generated by Django 4.1.2 on 2022-10-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_user_token_user_spotify_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(),
        ),
    ]
