# Generated by Django 4.1.2 on 2022-11-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_account',
            field=models.BooleanField(default=False),
        ),
    ]
